// @generated by tonic-prost-build. DO NOT EDIT.
// Regenerate: cargo test --test serverless_protos -- --ignored --nocapture
// This file is @generated by prost-build.
/// Configuration of a single dense (embedding) vector.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DenseVectorConfig {
    /// Dimensionality of the embedding, e.g. 512 (CLIP), 1536, 3072.
    #[prost(uint64, tag = "1")]
    pub size: u64,
    /// Distance metric used to compare vectors.
    #[prost(enumeration = "Distance", tag = "2")]
    pub distance: i32,
    /// Store several sub-vectors per point and compare with max-sim, for
    /// late-interaction models (ColBERT, ColPali, ...).
    #[prost(bool, tag = "3")]
    pub multivector: bool,
    /// Precision/cost trade-off for this vector. Unset: HIGH.
    #[prost(enumeration = "PrecisionTier", optional, tag = "4")]
    pub precision_tier: ::core::option::Option<i32>,
}
/// Configuration of a single sparse vector.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SparseVectorConfig {
    /// Apply the IDF modifier at query time. Enable for BM25-style models that
    /// expect inverse-document-frequency weighting.
    #[prost(bool, tag = "1")]
    pub use_idf: bool,
    /// Precision/cost trade-off for this vector. Unset: HIGH.
    #[prost(enumeration = "PrecisionTier", optional, tag = "2")]
    pub precision_tier: ::core::option::Option<i32>,
}
/// Exact match on string values, e.g. `color: "red"`.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct KeywordIndex {}
/// Exact match and/or range filters on integers, e.g. `age: 25`. Both are on
/// by default; turning one off shrinks the index.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IntegerIndex {
    /// Support exact-match filters.
    #[prost(bool, optional, tag = "1")]
    pub lookup: ::core::option::Option<bool>,
    /// Support range filters.
    #[prost(bool, optional, tag = "2")]
    pub range: ::core::option::Option<bool>,
}
/// Range filters on floating point (and integer) numbers, e.g. `price: 99.5`.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FloatIndex {}
/// Exact match on UUID strings; like keyword but stored compactly.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UuidIndex {}
/// Range filters on RFC 3339 datetimes, e.g. `created_at: "2023-02-08T10:49:00Z"`.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DatetimeIndex {}
/// Full-text filtering on string values.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TextIndex {
    /// Tokenizer to split text with. Unset: WHITESPACE.
    #[prost(enumeration = "Tokenizer", optional, tag = "1")]
    pub tokenizer: ::core::option::Option<i32>,
    /// Lowercase text before indexing. Default true.
    #[prost(bool, optional, tag = "2")]
    pub lowercase: ::core::option::Option<bool>,
    /// Support phrase queries; extra index structure. Default true.
    #[prost(bool, optional, tag = "3")]
    pub phrase_matching: ::core::option::Option<bool>,
    /// Minimum token length to index.
    #[prost(uint64, optional, tag = "4")]
    pub min_token_len: ::core::option::Option<u64>,
    /// Maximum token length to index.
    #[prost(uint64, optional, tag = "5")]
    pub max_token_len: ::core::option::Option<u64>,
}
/// Geo radius / bounding box / polygon filters on `{lon, lat}` values.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GeoIndex {}
/// Exact match on booleans, e.g. `is_active: true`.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BoolIndex {}
/// One payload index. Only the *kind* of filter the field supports is chosen
/// here; storage placement of the index is the manager's decision.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PayloadIndexConfig {
    /// The kind of filter the field supports.
    #[prost(oneof = "payload_index_config::Index", tags = "1, 2, 3, 4, 5, 6, 7, 8")]
    pub index: ::core::option::Option<payload_index_config::Index>,
}
/// Nested message and enum types in `PayloadIndexConfig`.
pub mod payload_index_config {
    /// The kind of filter the field supports.
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Index {
        /// Exact match on strings.
        #[prost(message, tag = "1")]
        Keyword(super::KeywordIndex),
        /// Exact match and/or range filters on integers.
        #[prost(message, tag = "2")]
        Integer(super::IntegerIndex),
        /// Range filters on numbers.
        #[prost(message, tag = "3")]
        Float(super::FloatIndex),
        /// Exact match on UUIDs.
        #[prost(message, tag = "4")]
        Uuid(super::UuidIndex),
        /// Range filters on datetimes.
        #[prost(message, tag = "5")]
        Datetime(super::DatetimeIndex),
        /// Full-text filtering.
        #[prost(message, tag = "6")]
        Text(super::TextIndex),
        /// Geo filters.
        #[prost(message, tag = "7")]
        Geo(super::GeoIndex),
        /// Exact match on booleans.
        #[prost(message, tag = "8")]
        Bool(super::BoolIndex),
    }
}
/// The tenant's collection config. Persisted verbatim. At least one dense or
/// sparse vector is required.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CollectionConfig {
    /// Keyed by vector name. The empty name "" is the unnamed default vector, as
    /// in qdrant; a collection either has the single unnamed vector or named ones.
    #[prost(map = "string, message", tag = "1")]
    pub dense_vectors: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        DenseVectorConfig,
    >,
    /// Keyed by vector name.
    #[prost(map = "string, message", tag = "2")]
    pub sparse_vectors: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        SparseVectorConfig,
    >,
    /// Keyed by payload field name (JSON path, e.g. `user_id` or `meta.tags`).
    #[prost(map = "string, message", tag = "3")]
    pub payload_indexes: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        PayloadIndexConfig,
    >,
}
/// Every request names the collection by its tenant-facing name only. The
/// tenant (`x-account-id`, `x-space-id`) travels in gRPC metadata, injected by
/// auth. The storage id is the manager's: minted on create, resolved
/// internally on get/delete.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateCollectionRequest {
    /// Tenant-facing name of the collection to create.
    #[prost(string, tag = "1")]
    pub collection_name: ::prost::alloc::string::String,
    /// The collection's configuration.
    #[prost(message, optional, tag = "2")]
    pub config: ::core::option::Option<CollectionConfig>,
}
/// Result of a create.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateCollectionResponse {
    /// Tenant-facing name of the collection.
    #[prost(string, tag = "1")]
    pub collection_name: ::prost::alloc::string::String,
    /// Outcome, e.g. "created", "already exists".
    #[prost(string, tag = "2")]
    pub result: ::prost::alloc::string::String,
}
/// Names the collection to delete.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteCollectionRequest {
    /// Tenant-facing name of the collection to delete.
    #[prost(string, tag = "1")]
    pub collection_name: ::prost::alloc::string::String,
}
/// Result of a delete.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteCollectionResponse {
    /// Whether the collection existed and was deleted.
    #[prost(bool, tag = "1")]
    pub deleted: bool,
    /// Number of storage objects removed.
    #[prost(uint32, tag = "2")]
    pub objects_deleted: u32,
}
/// Names the collection to fetch.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetCollectionRequest {
    /// Tenant-facing name of the collection.
    #[prost(string, tag = "1")]
    pub collection_name: ::prost::alloc::string::String,
}
/// The collection's configuration and stats, if it exists.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetCollectionResponse {
    /// Whether the collection exists.
    #[prost(bool, tag = "1")]
    pub exists: bool,
    /// The configuration the collection was created with.
    #[prost(message, optional, tag = "2")]
    pub config: ::core::option::Option<CollectionConfig>,
    /// Available points as of the last applied write (eventually consistent);
    /// absent until the updater has written stats for the collection.
    #[prost(uint64, optional, tag = "3")]
    pub point_count: ::core::option::Option<u64>,
}
/// Lists the caller's collections. The tenant travels in metadata, so there is
/// nothing to name here.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListCollectionsRequest {}
/// One collection in a listing.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CollectionSummary {
    /// Tenant-facing name of the collection.
    #[prost(string, tag = "1")]
    pub collection_name: ::prost::alloc::string::String,
    /// Available points as of the last applied write (eventually consistent);
    /// absent until the updater has written stats for the collection.
    #[prost(uint64, optional, tag = "2")]
    pub point_count: ::core::option::Option<u64>,
}
/// The caller's collections.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListCollectionsResponse {
    /// Ordered by name. A collection whose creation never published a manifest is
    /// not listed: it is not servable.
    #[prost(message, repeated, tag = "1")]
    pub collections: ::prost::alloc::vec::Vec<CollectionSummary>,
}
/// Distance metric used to compare dense vectors.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Distance {
    /// Unset; a concrete metric is required.
    Unspecified = 0,
    /// Cosine similarity.
    Cosine = 1,
    /// Euclidean (L2) distance.
    Euclid = 2,
    /// Dot product.
    Dot = 3,
    /// Manhattan (L1) distance.
    Manhattan = 4,
}
impl Distance {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "DISTANCE_UNSPECIFIED",
            Self::Cosine => "COSINE",
            Self::Euclid => "EUCLID",
            Self::Dot => "DOT",
            Self::Manhattan => "MANHATTAN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DISTANCE_UNSPECIFIED" => Some(Self::Unspecified),
            "COSINE" => Some(Self::Cosine),
            "EUCLID" => Some(Self::Euclid),
            "DOT" => Some(Self::Dot),
            "MANHATTAN" => Some(Self::Manhattan),
            _ => None,
        }
    }
}
/// How much of the original vector precision may be traded for cost. The manager
/// turns this into a concrete quantization / datatype choice; the tenant never
/// picks scalar/product/binary quantization or its parameters directly.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PrecisionTier {
    /// Unset: HIGH.
    Unspecified = 0,
    /// Aggressive compression, lowest cost, approximate results.
    Low = 1,
    /// Moderate compression with a small accuracy trade-off.
    Medium = 2,
    /// No lossy compression: exact stored vectors.
    High = 3,
}
impl PrecisionTier {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PRECISION_TIER_UNSPECIFIED",
            Self::Low => "LOW",
            Self::Medium => "MEDIUM",
            Self::High => "HIGH",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PRECISION_TIER_UNSPECIFIED" => Some(Self::Unspecified),
            "LOW" => Some(Self::Low),
            "MEDIUM" => Some(Self::Medium),
            "HIGH" => Some(Self::High),
            _ => None,
        }
    }
}
/// Full-text tokenizer, mirrors qdrant's `TokenizerType`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Tokenizer {
    /// Unset: WHITESPACE.
    Unspecified = 0,
    /// Index every prefix of each token.
    Prefix = 1,
    /// Split on whitespace.
    Whitespace = 2,
    /// Split on word boundaries.
    Word = 3,
    /// Language-aware tokenization.
    Multilingual = 4,
}
impl Tokenizer {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "TOKENIZER_UNSPECIFIED",
            Self::Prefix => "PREFIX",
            Self::Whitespace => "WHITESPACE",
            Self::Word => "WORD",
            Self::Multilingual => "MULTILINGUAL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TOKENIZER_UNSPECIFIED" => Some(Self::Unspecified),
            "PREFIX" => Some(Self::Prefix),
            "WHITESPACE" => Some(Self::Whitespace),
            "WORD" => Some(Self::Word),
            "MULTILINGUAL" => Some(Self::Multilingual),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod collections_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// CollectionsService manages the collections of a qdrant serverless space.
    /// Unlike the qdrant server API, it exposes only a simplified configuration:
    /// the manager turns it into concrete qdrant settings, which are never
    /// exposed to the tenant.
    #[derive(Debug, Clone)]
    pub struct CollectionsServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl CollectionsServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> CollectionsServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> CollectionsServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            CollectionsServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Creates a collection with the given tenant-facing configuration.
        pub async fn create_collection(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateCollectionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateCollectionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/qdrant.serverless.CollectionsService/CreateCollection",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "qdrant.serverless.CollectionsService",
                        "CreateCollection",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Deletes a collection and all of its data.
        pub async fn delete_collection(
            &mut self,
            request: impl tonic::IntoRequest<super::DeleteCollectionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteCollectionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/qdrant.serverless.CollectionsService/DeleteCollection",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "qdrant.serverless.CollectionsService",
                        "DeleteCollection",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Returns a single collection's configuration and stats.
        pub async fn get_collection(
            &mut self,
            request: impl tonic::IntoRequest<super::GetCollectionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetCollectionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/qdrant.serverless.CollectionsService/GetCollection",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "qdrant.serverless.CollectionsService",
                        "GetCollection",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Lists the caller's collections.
        pub async fn list_collections(
            &mut self,
            request: impl tonic::IntoRequest<super::ListCollectionsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListCollectionsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/qdrant.serverless.CollectionsService/ListCollections",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "qdrant.serverless.CollectionsService",
                        "ListCollections",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
