name: Formatter and linter

on: [ push ]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - name: Install minimal stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get install protobuf-compiler
      - name: Check code formatting
        run: cargo fmt --all -- --check
      - name: Check cargo clippy warnings
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings
