name: Publish

on:
  workflow_dispatch:
  push:
    # Pattern matched against refs/tags
    tags:
      - 'v*'           # Push events to every version tag

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install minimal stable
        uses: dtolnay/rust-toolchain@stable
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get install protobuf-compiler
      - name: Login
        run: cargo login ${{ secrets.CRATE_IO_API_TOKEN }}
      - name: Publish
        run: cargo publish
